// <auto-generated />
namespace Type2_TPC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sau : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sau));
        
        string IMigrationMetadata.Id
        {
            get { return "202011221125308_sau"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
